### ISSUE TITLE
Question: Looking at the redeem operations, are there concerns with a token holder burning their own tokens?

### ISSUE THREAD

**Issue by karimkawambwa** [ConsenSys/UniversalToken#104]
Hi there,

I am trying to follow the code and I see all the redeem operations eventually call `_callSenderExtension` and `_callTokenExtension` which make the calls `tokensToTransfer` and `tokensToValidate` respectively. 

Is the design ment to make use of the `userExtension` and implement `tokensToTransfer`  to stop user's from burning their own tokens?

I looked into `tokensToValidate` and it doesn't look like it would prevent this case.

**Comment by gauthierpetetin** [comment]
Hello @karimkawambwa ,
There is no implementation example of `userExtension` on this repo, but it is typically the place where you could setup logic to stop users from burning their own tokens.

**Comment by karimkawambwa** [comment]
Noted @gauthierpetetin, so a dev would also have to add logic in the `userExtension` to only allow a subset of operators to change token partitions? Not all operators should be allowed to do this operation.
