### ISSUE TITLE
Correct way to restrict transfer by partition

### ISSUE THREAD

**Issue by simbro** [ConsenSys/UniversalToken#119]
I am trying to create a token to represent a financial instrument that is semi-fungible, whereby tokens are fungible within tranches that each have specific restrictions.

From looking at the code, I can see that there is a function called [transferByPartition](https://github.com/ConsenSys/UniversalToken/blob/4206fcb7fec12f4eee216aaf2bc030c2c58763a7/contracts/ERC1400.sol#L820) which in turn calls a function named [_callTokenExtension](https://github.com/ConsenSys/UniversalToken/blob/4206fcb7fec12f4eee216aaf2bc030c2c58763a7/contracts/ERC1400.sol#L1028).

The `_callTokenExtension` function retrieves the address of the `ERC1400TokensChecker` contract that contains the business validation logic, by calling the function `interfaceAddr` on the `ERC1820Client` contract, which in turn looks up the address of this contract in the `ERC1820Registry` contract.

Once the contract has retrieved the address of the `ERC1400TokensChecker` contract from the `ERC1820Registry` contract, it calls the [tokenToValidate](https://github.com/ConsenSys/UniversalToken/blob/4206fcb7fec12f4eee216aaf2bc030c2c58763a7/contracts/extensions/tokenExtensions/ERC1400TokensValidator.sol#L292) function.  This function then applies various require statements which check partition granularity, certificates, holds, allow-lists etc.

**My question is this:  where would I incorporate custom functionality such as partition expiry dates for example?**

I can't see anywhere that I can call a custom contract containing bespoke logic for my specific business use case.

**Comment by gauthierpetetin** [comment]
Hi @simbro ,
Sorry for the late reply.
The recommended way to do this would be to write you own customized version of the [ERC1400TokensValidator](https://github.com/ConsenSys/UniversalToken/blob/4206fcb7fec12f4eee216aaf2bc030c2c58763a7/contracts/extensions/tokenExtensions/ERC1400TokensValidator.sol) and link the main token contract to it thanks to the [setTokenExtension](https://github.com/ConsenSys/UniversalToken/blob/4206fcb7fec12f4eee216aaf2bc030c2c58763a7/contracts/ERC1400.sol#L755) function.

**Comment by simbro** [comment]
No need to apologize - thanks for getting back to me.  I assumed that I would need to write my own version of the ERC1400TokensValidator contract, but I wasn't sure if I was missing something.  Thanks for confirming!
