### ISSUE TITLE
About ERC1400 Example Code , What is the role of "Controllers"

### ISSUE THREAD

**Issue by hamadayukinori** [ConsenSys/UniversalToken#31]
In ERC1400Raw.sol 
> address[] internal _controllers;

What does this definition mean? What can Contollers do ?

In contrast to Controllers, Operator can "operatorRedeemByPartition()" and  "operatorTransferByPartition" !

What is the difference between the two?

**Comment by gauthierpetetin** [comment]
An operator can act on behalf of other users (by calling operatorTransferByPartition, operatorRedeemByPartition, etc.).
There are 2 ways to be allowed to act as an operator, and act on behalf of a given user:
 - Being authorized by the given user (authorizeOperator, authorizeOperatorByPartition)
 - Being a controller (only when the contract is “controllable”)

In summary, when the contract is “controllable”, a controller can act on behalf of all users, without requiring a specific authorisation from them.
This property can be removed at any time by the contract owner, by making the contract “non-controllable” (renounceControl).
