### ISSUE TITLE
> ERC1820 deployment: Unknown error Error: nonce too low

### ISSUE THREAD

**Issue by jasonclinx** [ConsenSys/UniversalToken#32]
Hi did any one encounter this error?

I had this error when the deployment to ropsten went to the second file 2_erc1820_registry.js. The 3rd file 3_erc1400.js was deployed successfully, but I couldn't find the token generated on ropsten.

Here is the contract I deployed: https://ropsten.etherscan.io/address/0x9C7DbCcd5727C575a9d45601Ec078286Ff25c8c9

Thanks in advance.

**Comment by gauthierpetetin** [comment]
ERC1820 is a unique contract registry. It is deployed at a pre-defined address (0x1820a4b7618bde71dce8cdc73aab6c95905fad24).
2_erc1820_registry.js migration file is useful in cases where ERC1820 is not deployed, like on private networks.
But on ropsten it is already deployed:
https://ropsten.etherscan.io/address/0x1820a4b7618bde71dce8cdc73aab6c95905fad24
