### ISSUE TITLE
Deploying "ERC1400ERC20": ran out of gas

### ISSUE THREAD

**Issue by jasonclinx** [ConsenSys/UniversalToken#47]
```
"ERC1400ERC20" ran out of gas (using a value you set in your network config or deployment parameters.)
   * Block limit:  0x201c061
   * Gas sent:     6721975
```

Hi is there someone who knows the possible cause of the error of `truffle migrate`? 

After googling I enabled optimizer of `solc` in `truffle-config.js`, but still doesn't work.

```
compilers: {
    solc: {
       optimizer: {
         enabled: true,
         runs: 200
       }
    }
```

**Comment by victorwiebe** [comment]
ERC1400ERC20 has a very high gas usage, I have had trouble with it myself deploying from other contracts. In another thread we worked through this :

https://github.com/ConsenSys/ERC1400/issues/43#issuecomment-612426969

You can remove the  CertificateController functionality to reduce space, and depend on the ERC14000TokensValidator. I've been using the base ERC1400 contract up till now, but am considering making this change and using the ERC20 Backwards compatible version.

**Comment by jasonclinx** [comment]
@victorwiebe thanks Victor.

It turns out that it was because I did not type correctly in truffle-config.js. The optimizer of `solc` should be wrapped in a `settings` key, like:

```
compilers: {
    solc: {
       settings: {    // settings key
         optimizer: {
           enabled: true,
           runs: 200
...
```

**Comment by gauthierpetetin** [comment]
@jasonclinx , yes truffle-config.js needs to be configured with:
- solc optimizer enabled
- number of runs set to 0 (instead of 200 in your example)

The [example on this repo](https://github.com/ConsenSys/ERC1400/blob/master/truffle-config.js) shall work.
