### ISSUE TITLE
The documentation is not in sync with the implem

### ISSUE THREAD

**Issue by aBMania** [ConsenSys/UniversalToken#98]
Hello, I had a question about the lockHash in the ERC20HoldableToken contract.

https://github.com/ConsenSys/UniversalToken/blob/f82d0e1b39aaaebcf45c85c61f88f188311fde12/contracts/tokens/ERC20HoldableToken.sol#L128

In the comment of lockPreimage, it says that the hash algorithm is `keccak256` but below, it uses `sha256`.
```
holds[holdId].lockHash == sha256(abi.encodePacked(lockPreimage))
```

Which one is intended to be used?

**Comment by gauthierpetetin** [comment]
Thanks for flagging @aBMania : fixed in this [commit](https://github.com/ConsenSys/UniversalToken/commit/5b3bad4761f99470025c02f1f4d22b5c179cbaf0).
