### ISSUE TITLE
Cannot deploy on Quorum network

### ISSUE THREAD

**Issue by sadekyo1712** [ConsenSys/UniversalToken#99]
Hello everyone, now i have tried to deploy universal token to quorum network. But when i migrate smart contract code to network, i met error:

----
Deploying 'ERC1400'
transaction hash:    0x9246571b007675f90644869b1654d78898d0f32398676e15ad2809712a61b054

Error:  *** Deployment Failed ***

"ERC1400" received a generic error from Geth that
can be caused by hitting revert in a contract constructor or running out of gas.
   * Returned error: gas required exceeds allowance (90000000) or always failing transaction.
   * Try: + using the '--dry-run' option to reproduce this failure with clearer errors.
          + verifying that your gas is adequate for this deployment."
----

 Do anyone have met this error ? And how i can fix to deploy Universal token in quorum network ? Thanks in advance !

## Environment
- Version used: Truffle v5.1.49 (core: 5.1.49)
- Environment: Quorum, Node v10.15.3, Solidity - 0.5.10 (solc-js), Web3.js v1.2.1
- Server type and version:
- Operating System and version: Mac OS 11

**Comment by gauthierpetetin** [comment]
Hello @sadekyo1712 ,
Did you run the `yarn truffle migrate` command?
It is important to run it if you use your own network because it deploys ERC1820 registry in the [migration #2](https://github.com/ConsenSys/UniversalToken/blob/master/migrations/2_erc1820_registry.js).
Having ERC1820 registry deployed is a prerequisite before deploying the Universal Token.

**Comment by sadekyo1712** [comment]
Thanks you @gauthierpetetin for your reply. 
I have tried trufffle migrate and stuck at that step. After 1 day to troubleshoot, i have to change code in erc1820, it cannot to deploy on quorum network because of the gas price in quorum is 0. So the spec in ERC1820 is not valid when use in private network like quorum. Thanks u so much !
